In [25]:
import numpy as np

In [26]:
arr=np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [27]:
import time
size=1_000_000
python_list=list(range(size))
start=time.time()
square=[x**2 for x in python_list]
end=time.time()

In [28]:
print(f"Total time taken: {end-start}")

Total time taken: 0.12890362739562988


In [29]:
numpy_array=np.array(python_list)
start=time.time()
square_array=numpy_array**2
end=time.time()
print(f"Total time taken: {end-start}")

Total time taken: 0.003378152847290039


In [30]:
# which means that numpy take less time as comapared to python list therefore we use arrays
# instead of list while working with machine learning models

In [31]:
# checking for data homogenous
arr1=np.array([1,"Shayan"])
arr1

array(['1', 'Shayan'], dtype='<U21')

In [34]:
#2D Array
2d_array=np.array([[
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
2d_array

SyntaxError: invalid decimal literal (568531625.py, line 2)

In [35]:
arr3=np.full((2,2),75)
arr3

array([[75, 75],
       [75, 75]])

In [38]:
indentity=np.eye(4)
indentity

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])