In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [3]:
import time
size=1_000_000
python_list=list(range(size))
start=time.time()
square=[x**2 for x in python_list]
end=time.time()

In [4]:
print(f"Total time taken: {end-start}")

Total time taken: 0.1327528953552246


In [5]:
numpy_array=np.array(python_list)
start=time.time()
square_array=numpy_array**2
end=time.time()
print(f"Total time taken: {end-start}")

Total time taken: 0.015621662139892578


In [6]:
# which means that numpy take less time as comapared to python list therefore we use arrays
# instead of list while working with machine learning models

In [7]:
# checking for data homogenous
arr1=np.array([1,"Shayan"])
arr1

array(['1', 'Shayan'], dtype='<U21')

In [8]:
two_d_array = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(two_d_array)
two_d_array.shape

[[1 2 3]
 [4 5 6]
 [7 8 9]]


(3, 3)

In [9]:
arr3=np.full((2,2),75)
arr3

array([[75, 75],
       [75, 75]])

In [10]:
indentity=np.eye(4)
indentity

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [13]:
flat_array=two_d_array.flatten()
flat_array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
import numpy as np

two_d_array = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(two_d_array)

flat_array = two_d_array.flatten()

print(flat_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]


In [14]:
print(flat_array[0])

1


In [18]:
print(two_d_array[1][1])

5


In [19]:
print(two_d_array[2][1])

8


In [21]:
idx=[1,2,5]
print(flat_array[idx])

[2 3 6]


In [27]:
idx = [0, 2]
print(two_d_array[:,idx])

[[1 3]
 [4 6]
 [7 9]]


In [28]:
arrary4=np.array([1,2,3,4,5,6,7,8,9,10])
print(arrary4[arrary4>5])

[ 6  7  8  9 10]


In [32]:
python_list=[1,2,3,4,5]
sub_list=python_list[1:4]
sub_list
change=sub_list[0]=200
print(sub_list)
print(change)
print(python_list)

[200, 3, 4]
200
[1, 2, 3, 4, 5]


In [35]:
arr=np.array([1,2,3,4,5])
sub_Arr=arr[1:4]
print(sub_Arr)
sub_Arr[0]=200
print(sub_Arr)
print(arr)

[2 3 4]
[200   3   4]
[  1 200   3   4   5]


In [37]:
arr=np.array([1,2,3,4,5])
sub_Arr=arr[1:4].copy()
print(sub_Arr)
sub_Arr[0]=200
print(sub_Arr)
print(arr)

[2 3 4]
[200   3   4]
[1 2 3 4 5]
